spring:
  application:
    name: blog-boot

management:
  endpoints:
    web:
      base-path: /admin

server:
  servlet:
    context-path: /
  port: 8443
  ssl:
    key-store-type: PKCS12
    # This keystore contains SSL cert for domain and needs to be placed side by side of the jar
    key-store: file:./usmans.info.pfx

