spring:
  application:
    name: blog-boot

management:
  endpoints:
    web:
      base-path: /admin

server:
  servlet:
    context-path: /
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: file:./usmans.info.pfx

